### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by horazont** [horazont/prometheus-xmpp-blackbox-exporter#4]
After about two days of operation, it has accumulated 1.8 GiB of RSS. This seems very excessive.

**Comment by hnrd** [comment]
I run a3ce328d, process uptime 46h (dockered), checking c2s_normal_auth from example.yml on two servers every 30 seconds. RSS is about 8 MiB. If that helps :)

**Comment by horazont** [comment]
@hnrd Thanks for sharing. Which probers do you use? I suspect the ping prober might be the culprit.
